[package]
name = "vadl-cosim-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
cosim-lib = { path = "../cosim-lib" }
anyhow = "1.0.98"

tracing = { version = "0.1.41", features = ["attributes"] }
tracing-subscriber = "0.3.19"
figment = { version = "0.10.19", features = ["toml"] }
clap = { version = "4.5.42", features = ["derive"] }
rusqlite = "0.37.0"
cursive = { version = "0.21.1", features = ["toml"] }
