
def NZCV_N : Register<"NZCV_N">
{
    let Namespace = "aarch64temp";
    let AsmName = "NZCV_N";
    let AltNames = [   ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 0 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;


    let HWEncoding = 0;

    let isArtificial = 0;
}
def NZCV_Z : Register<"NZCV_Z">
{
    let Namespace = "aarch64temp";
    let AsmName = "NZCV_Z";
    let AltNames = [   ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 1 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;


    let HWEncoding = 0;

    let isArtificial = 0;
}
def NZCV_C : Register<"NZCV_C">
{
    let Namespace = "aarch64temp";
    let AsmName = "NZCV_C";
    let AltNames = [   ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 2 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;


    let HWEncoding = 0;

    let isArtificial = 0;
}
def NZCV_V : Register<"NZCV_V">
{
    let Namespace = "aarch64temp";
    let AsmName = "NZCV_V";
    let AltNames = [   ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 3 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;


    let HWEncoding = 0;

    let isArtificial = 0;
}
def CurrentEL : Register<"CurrentEL">
{
    let Namespace = "aarch64temp";
    let AsmName = "CurrentEL";
    let AltNames = [   ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 4 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;


    let HWEncoding = 0;

    let isArtificial = 0;
}
def SPSel : Register<"SPSel">
{
    let Namespace = "aarch64temp";
    let AsmName = "SPSel";
    let AltNames = [   ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 5 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;


    let HWEncoding = 0;

    let isArtificial = 0;
}
def SP_EL0 : Register<"SP_EL0">
{
    let Namespace = "aarch64temp";
    let AsmName = "SP_EL0";
    let AltNames = [   ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 6 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;


    let HWEncoding = 0;

    let isArtificial = 0;
}
def SP_EL1 : Register<"SP_EL1">
{
    let Namespace = "aarch64temp";
    let AsmName = "SP_EL1";
    let AltNames = [   ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 7 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;


    let HWEncoding = 0;

    let isArtificial = 0;
}
def ELR_EL1 : Register<"ELR_EL1">
{
    let Namespace = "aarch64temp";
    let AsmName = "ELR_EL1";
    let AltNames = [   ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 8 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;


    let HWEncoding = 0;

    let isArtificial = 0;
}
def VBAR_EL1 : Register<"VBAR_EL1">
{
    let Namespace = "aarch64temp";
    let AsmName = "VBAR_EL1";
    let AltNames = [   ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 9 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;


    let HWEncoding = 0;

    let isArtificial = 0;
}
def ESR_EL1 : Register<"ESR_EL1">
{
    let Namespace = "aarch64temp";
    let AsmName = "ESR_EL1";
    let AltNames = [   ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 10 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;


    let HWEncoding = 0;

    let isArtificial = 0;
}
def SPSR_EL1 : Register<"SPSR_EL1">
{
    let Namespace = "aarch64temp";
    let AsmName = "SPSR_EL1";
    let AltNames = [   ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 11 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;


    let HWEncoding = 0;

    let isArtificial = 0;
}
def PC : Register<"PC">
{
    let Namespace = "aarch64temp";
    let AsmName = "PC";
    let AltNames = [   ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 12 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;


    let HWEncoding = 0;

    let isArtificial = 0;
}
def S0 : Register<"S0">
{
    let Namespace = "aarch64temp";
    let AsmName = "X0";
    let AltNames = [ "X0"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 15 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 0;


    let isArtificial = 0;
}
def S1 : Register<"S1">
{
    let Namespace = "aarch64temp";
    let AsmName = "X1";
    let AltNames = [ "X1"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 16 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 1;


    let isArtificial = 0;
}
def S2 : Register<"S2">
{
    let Namespace = "aarch64temp";
    let AsmName = "X2";
    let AltNames = [ "X2"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 17 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 2;


    let isArtificial = 0;
}
def S3 : Register<"S3">
{
    let Namespace = "aarch64temp";
    let AsmName = "X3";
    let AltNames = [ "X3"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 18 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 3;


    let isArtificial = 0;
}
def S4 : Register<"S4">
{
    let Namespace = "aarch64temp";
    let AsmName = "X4";
    let AltNames = [ "X4"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 19 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 4;


    let isArtificial = 0;
}
def S5 : Register<"S5">
{
    let Namespace = "aarch64temp";
    let AsmName = "X5";
    let AltNames = [ "X5"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 20 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 5;


    let isArtificial = 0;
}
def S6 : Register<"S6">
{
    let Namespace = "aarch64temp";
    let AsmName = "X6";
    let AltNames = [ "X6"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 21 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 6;


    let isArtificial = 0;
}
def S7 : Register<"S7">
{
    let Namespace = "aarch64temp";
    let AsmName = "X7";
    let AltNames = [ "X7"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 22 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 7;


    let isArtificial = 0;
}
def S8 : Register<"S8">
{
    let Namespace = "aarch64temp";
    let AsmName = "X8";
    let AltNames = [ "X8"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 23 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 8;


    let isArtificial = 0;
}
def S9 : Register<"S9">
{
    let Namespace = "aarch64temp";
    let AsmName = "X9";
    let AltNames = [ "X9"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 24 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 9;


    let isArtificial = 0;
}
def S10 : Register<"S10">
{
    let Namespace = "aarch64temp";
    let AsmName = "X10";
    let AltNames = [ "X10"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 25 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 10;


    let isArtificial = 0;
}
def S11 : Register<"S11">
{
    let Namespace = "aarch64temp";
    let AsmName = "X11";
    let AltNames = [ "X11"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 26 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 11;


    let isArtificial = 0;
}
def S12 : Register<"S12">
{
    let Namespace = "aarch64temp";
    let AsmName = "X12";
    let AltNames = [ "X12"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 27 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 12;


    let isArtificial = 0;
}
def S13 : Register<"S13">
{
    let Namespace = "aarch64temp";
    let AsmName = "X13";
    let AltNames = [ "X13"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 28 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 13;


    let isArtificial = 0;
}
def S14 : Register<"S14">
{
    let Namespace = "aarch64temp";
    let AsmName = "X14";
    let AltNames = [ "X14"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 29 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 14;


    let isArtificial = 0;
}
def S15 : Register<"S15">
{
    let Namespace = "aarch64temp";
    let AsmName = "X15";
    let AltNames = [ "X15"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 30 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 15;


    let isArtificial = 0;
}
def S16 : Register<"S16">
{
    let Namespace = "aarch64temp";
    let AsmName = "X16";
    let AltNames = [ "X16"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 31 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 16;


    let isArtificial = 0;
}
def S17 : Register<"S17">
{
    let Namespace = "aarch64temp";
    let AsmName = "X17";
    let AltNames = [ "X17"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 32 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 17;


    let isArtificial = 0;
}
def S18 : Register<"S18">
{
    let Namespace = "aarch64temp";
    let AsmName = "X18";
    let AltNames = [ "X18"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 33 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 18;


    let isArtificial = 0;
}
def S19 : Register<"S19">
{
    let Namespace = "aarch64temp";
    let AsmName = "X19";
    let AltNames = [ "X19"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 34 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 19;


    let isArtificial = 0;
}
def S20 : Register<"S20">
{
    let Namespace = "aarch64temp";
    let AsmName = "X20";
    let AltNames = [ "X20"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 35 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 20;


    let isArtificial = 0;
}
def S21 : Register<"S21">
{
    let Namespace = "aarch64temp";
    let AsmName = "X21";
    let AltNames = [ "X21"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 36 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 21;


    let isArtificial = 0;
}
def S22 : Register<"S22">
{
    let Namespace = "aarch64temp";
    let AsmName = "X22";
    let AltNames = [ "X22"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 37 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 22;


    let isArtificial = 0;
}
def S23 : Register<"S23">
{
    let Namespace = "aarch64temp";
    let AsmName = "X23";
    let AltNames = [ "X23"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 38 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 23;


    let isArtificial = 0;
}
def S24 : Register<"S24">
{
    let Namespace = "aarch64temp";
    let AsmName = "X24";
    let AltNames = [ "X24"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 39 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 24;


    let isArtificial = 0;
}
def S25 : Register<"S25">
{
    let Namespace = "aarch64temp";
    let AsmName = "X25";
    let AltNames = [ "X25"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 40 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 25;


    let isArtificial = 0;
}
def S26 : Register<"S26">
{
    let Namespace = "aarch64temp";
    let AsmName = "X26";
    let AltNames = [ "X26"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 41 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 26;


    let isArtificial = 0;
}
def S27 : Register<"S27">
{
    let Namespace = "aarch64temp";
    let AsmName = "X27";
    let AltNames = [ "X27"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 42 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 27;


    let isArtificial = 0;
}
def S28 : Register<"S28">
{
    let Namespace = "aarch64temp";
    let AsmName = "X28";
    let AltNames = [ "X28"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 43 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 28;


    let isArtificial = 0;
}
def S29 : Register<"S29">
{
    let Namespace = "aarch64temp";
    let AsmName = "A_FP";
    let AltNames = [ "A_FP"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 44 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 29;


    let isArtificial = 0;
}
def S30 : Register<"S30">
{
    let Namespace = "aarch64temp";
    let AsmName = "A_LR";
    let AltNames = [ "A_LR"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 45 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 30;


    let isArtificial = 0;
}
def S31 : Register<"S31">
{
    let Namespace = "aarch64temp";
    let AsmName = "A_SP";
    let AltNames = [ "A_SP"  ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 46 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;

    let HWEncoding{4-0} = 31;


    let isArtificial = 0;
}



def SP : Register<"SP">
{
    let Namespace = "aarch64temp";
    let AsmName = "SP";
    let AltNames = [   ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 13 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;
    let HWEncoding = 31;
    let isArtificial = 1;
}
def LR : Register<"LR">
{
    let Namespace = "aarch64temp";
    let AsmName = "LR";
    let AltNames = [   ];
    let Aliases = [ ];
    let SubRegs = [ ];
    let SubRegIndices = [ ];
    let RegAltNameIndices = [];
    let DwarfNumbers = [ 14 ];
    list<int> CostPerUse = [0];
    let CoveredBySubRegs = 0;
    let HWEncoding = 30;
    let isArtificial = 1;
}


defvar aarch64temp = DefaultMode;

def SLenRI : RegInfoByHwMode<
      [ aarch64temp ],
      [RegInfo<64,64,64>]>;
def S : RegisterClass
< /* namespace = */ "aarch64temp"
, /* regTypes  = */  [  i64 ]
, /* alignment = */ 32
, /* regList   = */
  ( add S9, S10, S11, S12, S13, S14, S15, S19, S20, S21, S22, S23, S24, S25, S26, S27, S28, S0, S1, S2, S3, S4, S5, S6, S7, S8, S16, S17, S18, S29, S30, S31 )
> {
  let RegInfos = SLenRI;
}

