// SPDX-FileCopyrightText : © 2025 TU Wien <vadl@tuwien.ac.at>
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package vadl.gcb.passes.relocation.model;

import static vadl.viam.ViamError.ensure;

import java.util.List;
import javax.annotation.Nullable;
import vadl.cppCodeGen.model.GcbImmediateExtractionCppFunction;
import vadl.cppCodeGen.model.GcbUpdateFieldRelocationCppFunction;
import vadl.gcb.valuetypes.VariantKind;
import vadl.types.Type;
import vadl.utils.SourceLocation;
import vadl.viam.Format;
import vadl.viam.Function;
import vadl.viam.Identifier;
import vadl.viam.Instruction;
import vadl.viam.Parameter;
import vadl.viam.Relocation;
import vadl.viam.graph.control.ReturnNode;
import vadl.viam.graph.dependency.FuncParamNode;

/**
 * {@link AutomaticallyGeneratedRelocation} are relocations which were
 * generated by the VADL compiler.
 */
public class AutomaticallyGeneratedRelocation extends CompilerRelocation
    implements HasRelocationComputationAndUpdate, RelocationsBeforeElfExpansion {
  protected final Instruction instruction;
  protected final Modifier modifier;
  protected final VariantKind variantKind;
  // This is the function which computes the value for the
  // relocation.
  protected final GcbImmediateExtractionCppFunction valueRelocation;
  // This is the function which updates the value in the format.
  protected final GcbUpdateFieldRelocationCppFunction fieldUpdateFunction;

  protected final Format.FieldAccess fieldAccess;
  protected final Format format;

  @Nullable
  protected Fixup fixup;

  /**
   * Constructor.
   */
  public static AutomaticallyGeneratedRelocation create(
      Instruction instruction,
      Kind kind,
      Modifier modifier,
      VariantKind variantKind,
      Format format,
      Format.FieldAccess fieldAccess,
      GcbUpdateFieldRelocationCppFunction
          fieldUpdateFunction) {
    var identifier = generateName(format, instruction, fieldAccess, kind);
    var parameter = new Parameter(new Identifier("input",
        SourceLocation.INVALID_SOURCE_LOCATION),
        Type.signedInt(64),
        0); // default in LLVM, otherwise we might get truncation
    var relocation =
        new Relocation(identifier, kind.map(), new Parameter[] {parameter}, format.type());
    var valueRelocation = createGcbRelocationCppFunction(relocation);
    valueRelocation.behavior().addWithInputs(new ReturnNode(new FuncParamNode(parameter)));
    return new AutomaticallyGeneratedRelocation(
        instruction,
        identifier,
        kind,
        modifier,
        variantKind,
        format,
        fieldAccess,
        relocation,
        valueRelocation,
        fieldUpdateFunction);
  }

  /**
   * Wraps the {@code function} into a {@link GcbImmediateExtractionCppFunction}.
   */
  public static GcbImmediateExtractionCppFunction createGcbRelocationCppFunction(
      Function function) {
    return new GcbImmediateExtractionCppFunction(function.identifier,
        function.parameters(),
        Type.signedInt(64), // default in LLVM, otherwise we might get truncation
        function.behavior());
  }

  private AutomaticallyGeneratedRelocation(
      Instruction instruction,
      Identifier identifier,
      Kind kind,
      Modifier modifier,
      VariantKind variantKind,
      Format format,
      Format.FieldAccess fieldAccess,
      Relocation relocationRef,
      GcbImmediateExtractionCppFunction valueRelocation,
      GcbUpdateFieldRelocationCppFunction fieldUpdateFunction
  ) {
    super(identifier, kind, relocationRef);
    this.instruction = instruction;
    this.modifier = modifier;
    this.variantKind = variantKind;
    this.format = format;
    this.fieldAccess = fieldAccess;
    this.valueRelocation = valueRelocation;
    this.fieldUpdateFunction = fieldUpdateFunction;
  }

  private static Identifier generateName(Format format,
                                         Instruction instruction,
                                         Format.FieldAccess fieldAccess,
                                         Kind kind) {
    return format.identifier.append(kind.name(),
        instruction.identifier.simpleName(),
        fieldAccess.identifier.simpleName());
  }

  public Instruction instruction() {
    return instruction;
  }

  @Override
  public GcbImmediateExtractionCppFunction valueRelocation() {
    return valueRelocation;
  }

  @Override
  public GcbUpdateFieldRelocationCppFunction fieldUpdateFunction() {
    return fieldUpdateFunction;
  }

  @Override
  public Identifier identifier() {
    return identifier;
  }

  @Override
  public Modifier modifier() {
    return modifier;
  }

  @Override
  public VariantKind variantKind() {
    return variantKind;
  }

  @Override
  public Relocation relocation() {
    return relocationRef;
  }

  /**
   * Set fixup for this relocation.
   * Cannot be done in constructor because fixup and
   * {@link HasRelocationComputationAndUpdate} reference each other.
   */
  public void setFixup(Fixup fixup) {
    this.fixup = fixup;
  }

  @Override
  public Fixup fixup() {
    ensure(fixup != null,
        "Fixup must be set before calling fixup()");
    return fixup;
  }

  @Override
  public List<Format.Field> fields() {
    return fieldAccess.fieldRefs();
  }

  public Format.FieldAccess fieldAccess() {
    return fieldAccess;
  }

  @Override
  public Format format() {
    return format;
  }

  @Override
  public CompilerRelocation.Kind kind() {
    return kind;
  }
}
