FROM kper1337/riscv32-spike-lcb-test@sha256:a2796985bb2c491a8922710b1097837636b0c182539e2f8dde3a6270f19cf060
ARG TARGET
ARG SCCACHE_REDIS_ENDPOINT
ARG UPSTREAM_BUILD_TARGET
ENV TARGET=${TARGET}
ENV LLVM_UPSTREAM_TARGETS=${UPSTREAM_BUILD_TARGET}
ENV SCCACHE_REDIS_ENDPOINT=${SCCACHE_REDIS_ENDPOINT}
RUN apt-get update -y
RUN apt-get install -y vim
COPY . /src
WORKDIR /src
RUN mv /opt/sccache/sccache /usr/bin/sccache
RUN make && sccache -s
CMD sh /src/embench/benchmark-extras/run-benchmarks-spike-clang-lcb.sh