[versions]
kotlin = "2.3.0"
guava = "33.2.1-jre"
thymeleaf = "3.1.2.RELEASE"
commonsIo = "2.16.1"
commonsLang3 = "3.18.0"
commonsText = "1.10.0"
z3Bootstrap = "1.0.0"
junit5 = "5.11.4"
junit5_510 = "5.10.0"
assertj = "3.26.3"
awaitility = "4.2.1"
testcontainers = "1.21.4"
archunit = "1.4.1"
velocity = "2.3"
jqwik = "1.9.0"
snakeyaml = "2.2"
picocli = "4.7.6"
commonsCompress = "1.27.1"
lsp4j = "0.24.0"
autoService = "1.1.1"
errorProneApi = "2.26.1"
errorProne = "2.43.0"
nullaway = "0.10.25"
jsr305 = "3.0.2"
jetbrainsAnnotations = "24.0.1"
logback = "1.5.24"
checkstyle = "10.15.0"
gitVersioning = "6.4.4"
testLogger = "4.0.0"
errorpronePlugin = "4.3.0"
foojayResolver = "0.7.0"
z3Plugin = "1.0.2"
graalvmPlugin = "0.11.2"
jlinkPlugin = "3.2.0"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
thymeleaf = { module = "org.thymeleaf:thymeleaf", version.ref = "thymeleaf" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang3" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commonsText" }
z3-bootstrap = { module = "io.github.rascmatt:z3-bootstrap", version.ref = "z3Bootstrap" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit5" }
junit-bom510 = { module = "org.junit:junit-bom", version.ref = "junit5_510" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
archunit = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
velocity = { module = "org.apache.velocity:velocity-engine-core", version.ref = "velocity" }
jqwik = { module = "net.jqwik:jqwik", version.ref = "jqwik" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commonsCompress" }
lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4j" }
auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoService" }
auto-service = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }

errorprone-api = { module = "com.google.errorprone:error_prone_check_api", version.ref = "errorProneApi" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorProne" }
errorprone-annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "errorProne" }
errorprone-plugin = { module = "net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin", version.ref = "errorpronePlugin" }

jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorpronePlugin" }
test-logger = { id = "com.adarshr.test-logger", version.ref = "testLogger" }
git-versioning = { id = "me.qoomon.git-versioning", version.ref = "gitVersioning" }
foojay-resolver = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojayResolver" }
z3 = { id = "io.github.rascmatt.z3", version.ref = "z3Plugin" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvmPlugin" }
jlink = { id = "org.beryx.jlink", version.ref = "jlinkPlugin" }


# build-logic / gradle-conventions project
conventions-cocor = { id = "conventions-cocor" }
conventions-root = { id = "conventions-root" }
conventions-java = { id = "conventions-java" }