[versions]
kotlin = "2.3.0"
git-versioning = "6.4.4"
z3-plugin = "1.0.2"
graalvm-native = "0.11.2"
jlink = "3.2.0"
errorprone-plugin = "4.3.0"
test-logger-plugin = "4.0.0"
idea-ext-plugin = "1.1.10"
nullaway = "0.10.25"
errorprone = "2.43.0"
jsr305 = "3.0.2"
jetbrains-annotations = "24.0.1"
logback = "1.5.24"
junit = "5.11.4"
auto-service = "1.1.1"
errorprone-check-api = "2.26.1"
thymeleaf = "3.1.2.RELEASE"
guava = "33.2.1-jre"
commons-io = "2.16.1"
commons-lang3 = "3.18.0"
commons-text = "1.10.0"
z3-bootstrap = "1.0.0"
buildkitcli = "0.14.0"
assertj = "3.26.3"
awaitility = "4.2.1"
testcontainers = "2.0.3"
archunit = "1.4.1"
velocity = "2.3"
jqwik = "1.9.0"
snakeyaml = "2.2"
picocli = "4.7.6"
commons-compress = "1.27.1"
lsp4j = "0.24.0"

[libraries]
gradle-errorprone-plugin = { module = "net.ltgt.gradle:gradle-errorprone-plugin", version.ref = "errorprone-plugin" }
gradle-test-logger-plugin = { module = "com.adarshr:gradle-test-logger-plugin", version.ref = "test-logger-plugin" }
idea-ext-gradle-plugin = { module = "org.jetbrains.gradle.plugin.idea-ext:org.jetbrains.gradle.plugin.idea-ext.gradle.plugin", version.ref = "idea-ext-plugin" }

nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
errorprone-annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "errorprone" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "auto-service" }
auto-service = { module = "com.google.auto.service:auto-service", version.ref = "auto-service" }
errorprone-check-api = { module = "com.google.errorprone:error_prone_check_api", version.ref = "errorprone-check-api" }

thymeleaf = { module = "org.thymeleaf:thymeleaf", version.ref = "thymeleaf" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
z3-bootstrap = { module = "io.github.rascmatt:z3-bootstrap", version.ref = "z3-bootstrap" }
buildkitcli = { module = "io.github.kper:buildkitcli", version.ref = "buildkitcli" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
velocity-engine-core = { module = "org.apache.velocity:velocity-engine-core", version.ref = "velocity" }
jqwik = { module = "net.jqwik:jqwik", version.ref = "jqwik" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }

picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4j" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
git-versioning = { id = "me.qoomon.git-versioning", version.ref = "git-versioning" }
z3 = { id = "io.github.rascmatt.z3", version.ref = "z3-plugin" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvm-native" }
jlink = { id = "org.beryx.jlink", version.ref = "jlink" }
