#!/usr/bin/env python3

# This git hooks scripts validates that commit messages
# are not violating the commit message guidelines of
# https://ea.complang.tuwien.ac.at/vadl/vadl/issues/1573

import re
import sys


def validate_commit_message(message):
  # Split the commit message into header and body
  parts = message.split('\n\n', 1)
  header = parts[0]

  # Regular expression for header format: optional scope, capital letter, no period
  header_pattern = r'^(?:(\w+): )?[A-Z][^\n]*[^.\n]$'

  # Validate the header
  if not re.match(header_pattern, header):
    return False

  return True


# remove all lines starting with a #
def remove_comments(commit_message):
  lines = commit_message.split('\n')
  non_comment_lines = [line for line in lines if
                       not line.strip().startswith('#')]
  return '\n'.join(non_comment_lines)


def main(commit_msg_file):
  with open(commit_msg_file, 'r') as file:
    commit_message = file.read().strip()

  # remove all comment lines
  commit_message = remove_comments(commit_message)

  if not validate_commit_message(commit_message):
    print("Commit message does not follow the required format: \n[scope:] <description>\n\n[optional body]\n----")
    print("Ensure the description starts with a capital letter, is in imperative mood, and does not end with a period.")
    sys.exit(1)


if __name__ == "__main__":
  main(sys.argv[1])
