// SPDX-FileCopyrightText : © 2025 TU Wien <vadl@tuwien.ac.at>
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package vadl.rtl.passes;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Collection;
import java.util.function.Predicate;
import javax.annotation.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import vadl.configuration.RtlConfiguration;
import vadl.pass.PassName;
import vadl.pass.PassResults;
import vadl.rtl.template.RtlTemplateRenderingPass;
import vadl.template.AbstractMultiTemplateRenderingPass;
import vadl.viam.Specification;

/**
 * Remove scala files from the scala source directory in the RTL output folder, that were not
 * generated by the current run. This helps to not leave back files from old builds that would
 * cause the compilation of the generated project to fail.
 */
public class CleanupEmitDirectoryPass extends AbstractRtlPass {

  private static final Logger log = LoggerFactory.getLogger(CleanupEmitDirectoryPass.class);

  public CleanupEmitDirectoryPass(RtlConfiguration configuration) {
    super(configuration);
  }

  @Override
  public PassName getName() {
    return PassName.of("Clean Emit Directory");
  }

  @Nullable
  @Override
  public Object execute(PassResults passResults, Specification viam) throws IOException {

    var renderedFiles = passResults.allResultsOf(RtlTemplateRenderingPass.class,
            AbstractMultiTemplateRenderingPass.Result.class)
        .map(AbstractMultiTemplateRenderingPass.Result::emittedFiles)
        .flatMap(Collection::stream)
        .toList();

    clean(configuration().getScalaPackageDir(), path ->
        !renderedFiles.contains(path) && path.toString().endsWith(".scala"));

    return null;
  }

  private void clean(String directory, Predicate<Path> filter) {
    var dir = configuration().outputPath().resolve("rtl").resolve(directory);
    if (Files.exists(dir)) {
      try (var files = Files.list(dir)) {
        files.filter(Files::isRegularFile).filter(filter).forEach(file -> {
          try {
            Files.delete(file);
          } catch (IOException e) {
            log.warn("Could not remove file {} ({})", file, e.getMessage());
          }
        });
      } catch (IOException e) {
        log.warn("Could not remove files from {}", directory);
      }
    }
  }
}
