// SPDX-FileCopyrightText : © 2026 TU Wien <vadl@tuwien.ac.at>
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package vadl.lcb.passes.asm;

import java.util.List;
import java.util.Objects;
import java.util.Set;
import vadl.viam.asm.AsmToken;

/**
 * Captures the {@link AsmToken}s expected to be parsed in assembly grammar rules
 * generated by the {@link AsmGrammarRuleGenerator}.
 * This class allows to compare the syntaxes of generated rules against each other.
 */
public class AsmSyntax {
  private final List<Set<AsmToken>> tokenSets;

  public AsmSyntax(List<Set<AsmToken>> tokenSets) {
    this.tokenSets = tokenSets;
  }

  public List<Set<AsmToken>> getTokenSets() {
    return tokenSets;
  }

  public int numberOfTokenSets() {
    return tokenSets.size();
  }

  /**
   * Compare token sets of {@code this} and {@code other} AsmSyntax object.
   * Return the index of the first pair of token sets, where the intersection
   * of the two sets is empty.
   * If the two AsmSyntax objects have a non-empty intersection at every index return -1.
   *
   * @param other the AsmSyntax to compare {@code this} to
   * @return the first non-overlapping index or -1 if there is no such index
   */
  public int firstNonOverlappingIndex(AsmSyntax other) {
    int minSize = Math.min(tokenSets.size(), other.tokenSets.size());

    for (int i = 0; i < minSize; i++) {
      if (tokenSets.get(i).stream().noneMatch(other.tokenSets.get(i)::contains)) {
        return i;
      }
    }

    int maxSize = Math.max(tokenSets.size(), other.tokenSets.size());
    if (minSize == maxSize) {
      return -1;
    }

    return minSize;
  }

  @Override
  public boolean equals(Object o) {
    if (!(o instanceof AsmSyntax asmSyntax)) {
      return false;
    }

    return tokenSets.equals(asmSyntax.tokenSets);
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(tokenSets);
  }
}
