#!/usr/bin/env bash

OS=$(uname -s)

if [[ "$OS" = "Darwin" ]]; then
SED_I=(-i '')
else
SED_I=(-i'')
fi

DIR=$1

if [ -z "$DIR" ]; then
  echo not set
  exit 1
fi

# Check for the usual name of an output directory
EXPECTED_PART="obj/doc"
echo "$DIR" | grep -q $EXPECTED_PART || exit 1

REFMAN="$DIR"/refman.tex
AUTHORS="$DIR"/authors.tex

sed \
  "${SED_I[@]}" \
  -e '/{authors}/ s/^%*/%/' \
  -e '/chapter{Authors}/ s/^%*/%/' \
  "$REFMAN"

sed \
  "${SED_I[@]}" \
  's/\\input{authors.md}/\\input{authors}/g' \
  "$REFMAN"

sed \
  "${SED_I[@]}" \
-e 's/\\hline/%\\hline/g' \
-e 's/\\cline/%\\cline/g' \
-e 's/\\raggedleft/\\raggedleft\\large/g' \
-e '/\\tablehead/ s/^%*/%/' \
-e '/\\endfirsthead/ s/^%*/%/' \
-e '/\\endhead/ s/^%*/%/' \
-e '/\\endfoot/ s/^%*/%/' \
-e '/\\begin{longtabu}/ s/^%*/%/' \
-e '/\\end{longtabu}/ s/^%*/%/' \
-e '/\\tabulinesep/ s/^%*/%/' \
-e '/\\label{authors/ s/^%*/%/' \
-e '/\\Hypertarget{authors/ s/^%*/%/' \
"$AUTHORS"


# This is a bit safer than using cd to move to a dir
find "$DIR" -name "*.tex" -exec sed "${SED_I[@]}" \
  -e '/{\\footnotesize\\ttfamily/ s/^%*/%/' {} \;
