#!/usr/bin/env bash

set -e

CLANG_CFLAGS="--target=riscv32 -march=rv32im -mabi=ilp32"
LCB_CFLAGS="--target=rv32i -D__SIZEOF_POINTER__=4 -D__riscv_xlen=32"
CLANG=/llvm/build/bin/clang 

last="${@:(-1):1}"
extension="${last##*.}"
filename="${last%.*}"
basefilename=$(basename -- "$filename")

array=( "$@" )
unset "array[${#array[@]}-1]"
unset "array[${#array[@]}-1]"
unset "array[${#array[@]}-1]"

if [ $extension != "c" ]
then
  $CLANG $CLANG_CFLAGS -c $@
else
  $CLANG $LCB_CFLAGS -S   ${array[@]} -o $basefilename.s $last
  $CLANG $CLANG_CFLAGS -c ${array[@]} -o $basefilename.o $basefilename.s
fi
