[package]
name = "vadl-cosim-broker"
version = "0.1.0"
edition = "2024"

[features]
sqlite-tracing = ["cosim-lib/sqlite-tracing"]

[dependencies]
cosim-lib = { path = "../cosim-lib" }

clap = { version = "4.5.51", features = ["derive"] }
figment = { version = "0.10.19", features = ["toml"] }

tracing = { version = "0.1.41", features = ["attributes"] }
tracing-subscriber = "0.3.20"
serde_yaml = "0.9.34"
color-eyre = "0.6.5"
object = "0.38.1"
