package vadl.ast;

class Builtins {
  // TODO Replace with BuiltInTable
  static final String[] BUILTIN_FUNCTIONS = new String[] {
      "decimal",
      "hex",
      "register",
      "isInDelaySlot",

      // TODO Legacy functions, only needed for compatibility with old vadl files
      "VADL::mod", // Required by rv3264im, verify if necessary
      "VADL::div", // Required by miniARMv7, verify if necessary
      "VADL::asl", // Required by hexagon, verify if necessary
      "VADL::lth", // Required by mipsiv, verify if necessary
      "VADL::leq", // Required by mipsiv, verify if necessary
      "VADL::gth", // Required by mipsiv, verify if necessary
      "VADL::geq", // Required by mipsiv, verify if necessary

      "VADL::neg",
      "VADL::add",
      "VADL::adds",
      "VADL::addc",
      "VADL::ssatadd",
      "VADL::usatadd",
      "VADL::ssatadds",
      "VADL::usatadds",
      "VADL::ssataddc",
      "VADL::usataddc",
      "VADL::sub",
      "VADL::subsc",
      "VADL::subsb",
      "VADL::subc",
      "VADL::subb",
      "VADL::ssatsub",
      "VADL::usatsub",
      "VADL::ssatsubs",
      "VADL::usatsubs",
      "VADL::ssatsubc",
      "VADL::usatsubc",
      "VADL::ssatsubb",
      "VADL::usatsubb",
      "VADL::mul",
      "VADL::muls",
      "VADL::smull",
      "VADL::umull",
      "VADL::sumull",
      "VADL::smulls",
      "VADL::umulls",
      "VADL::sumulls",
      "VADL::smod",
      "VADL::umod",
      "VADL::smods",
      "VADL::umods",
      "VADL::sdiv",
      "VADL::udiv",
      "VADL::sdivs",
      "VADL::udivs",
      "VADL::not",
      "VADL::and",
      "VADL::ands",
      "VADL::xor",
      "VADL::xors",
      "VADL::or",
      "VADL::ors",
      "VADL::equ",
      "VADL::neq",
      "VADL::slth",
      "VADL::ulth",
      "VADL::sleq",
      "VADL::uleq",
      "VADL::sgth",
      "VADL::ugth",
      "VADL::sgeq",
      "VADL::ugeq",
      "VADL::lsl",
      "VADL::lsls",
      "VADL::lslc",
      "VADL::asr",
      "VADL::lsr",
      "VADL::asrs",
      "VADL::lsrs",
      "VADL::asrc",
      "VADL::lsrc",
      "VADL::rol",
      "VADL::rols",
      "VADL::rolc",
      "VADL::ror",
      "VADL::rors",
      "VADL::rorc",
      "VADL::rrx",
      "VADL::cob",
      "VADL::czb",
      "VADL::clz",
      "VADL::clo",
      "VADL::cls"
  };
}
