#
# Checkstyle Validation
#
kind: pipeline
type: docker
name: checkstyle

steps:
  - name: set gitea token
    image: c2.complang.tuwien.ac.at:5000/vadl-ci:f7222374638bccc355ba51bfcc2b17e9561204a4
    environment:
      ACCESS_TOKEN:
        from_secret: ACCESS_TOKEN
    commands:
      - git config --add --global url."https://$(ACCESS_TOKEN)@ea.complang.tuwien.ac.at/".insteadOf "git@ea.complang.tuwien.ac.at:"
      - git log -n 1 --oneline

  - name: build and checkstyle
    image: c2.complang.tuwien.ac.at:5000/vadl-ci:f7222374638bccc355ba51bfcc2b17e9561204a4
    commands:
      - ./gradlew checkstyleAll
  - name: test
    image: c2.complang.tuwien.ac.at:5000/vadl-ci:f7222374638bccc355ba51bfcc2b17e9561204a4
    privileged: true
    commands:
      - ./gradlew test
    volumes:
      - name: docker
        path: /var/run/docker.sock
  - name: comment checkstyle report
    image: c2.complang.tuwien.ac.at:5000/drone-gitea-message:1411b3d7e54329473da2717d2ef09a06f13b3bc4
    settings:
      api_key:
        from_secret: ACCESS_TOKEN
      base_url: https://ea.complang.tuwien.ac.at
      message_file: build/reports/checkstyle/report.md
      delete_identifier: checkstyle-report-delete-id
    when:
      status: [ failure ]

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

triggers:
  events:
    - pull_request
