#
# Drone pipeline of the open-vadl CI.
# It executes the following steps on updates to a pull request or pushes to master:
#   - build             ... fails on warnings and errors
#   - checkstyle        ... fails if there are checkstyle violations
#   - test              ... fails on failing tests
#   - checkstyle report ... runs on failure and comments the checkstyle report to the Gitea PR
#
kind: pipeline
type: docker
name: OpenVADL CI

steps:
  - name: set gitea token
    image: c2.complang.tuwien.ac.at:5000/vadl-ci:f7222374638bccc355ba51bfcc2b17e9561204a4
    environment:
      ACCESS_TOKEN:
        from_secret: ACCESS_TOKEN
    commands:
      - git config --add --global url."https://$(ACCESS_TOKEN)@ea.complang.tuwien.ac.at/".insteadOf "git@ea.complang.tuwien.ac.at:"
      - git log -n 1 --oneline

  - name: build
    image: c2.complang.tuwien.ac.at:5000/vadl-ci:f7222374638bccc355ba51bfcc2b17e9561204a4
    commands:
      - ./gradlew assemble testClasses -PFailOnWarnings
  - name: checkstyle
    image: c2.complang.tuwien.ac.at:5000/vadl-ci:f7222374638bccc355ba51bfcc2b17e9561204a4
    commands:
      - ./gradlew checkstyleAll
  - name: test
    image: c2.complang.tuwien.ac.at:5000/vadl-ci:f7222374638bccc355ba51bfcc2b17e9561204a4
    privileged: true
    commands:
      - ./gradlew test -i
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      isCI: true
  - name: comment checkstyle report
    image: c2.complang.tuwien.ac.at:5000/drone-gitea-message:1411b3d7e54329473da2717d2ef09a06f13b3bc4
    settings:
      api_key:
        from_secret: ACCESS_TOKEN
      base_url: https://ea.complang.tuwien.ac.at
      message_file: build/reports/checkstyle/report.md
      delete_identifier: checkstyle-report-delete-id
    when:
      status: [ failure ]

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock


trigger:
  ref:
    - refs/pull/**
    - refs/head/master

