#
# Drone pipeline of the open-vadl CI.
# It executes the following steps on updates to a pull request or pushes to master:
#   - build             ... fails on warnings and errors
#   - checkstyle        ... fails if there are checkstyle violations
#   - test              ... fails on failing tests
#   - checkstyle report ... runs on failure and comments the checkstyle report to the Gitea PR
#
kind: pipeline
type: docker
name: OpenVADL CI

steps:
  - name: set gitea token
    image: c2.complang.tuwien.ac.at:5000/vadl-ci:f7222374638bccc355ba51bfcc2b17e9561204a4
    environment:
      ACCESS_TOKEN:
        from_secret: ACCESS_TOKEN
    commands:
      - git config --add --global url."https://$(ACCESS_TOKEN)@ea.complang.tuwien.ac.at/".insteadOf "git@ea.complang.tuwien.ac.at:"
      - git log -n 1 --oneline

  - name: build
    image: c2.complang.tuwien.ac.at:5000/vadl-ci:f7222374638bccc355ba51bfcc2b17e9561204a4
    commands:
      - ./gradlew assemble testClasses -PFailOnWarnings
  - name: checkstyle
    image: c2.complang.tuwien.ac.at:5000/vadl-ci:f7222374638bccc355ba51bfcc2b17e9561204a4
    commands:
      - ./gradlew checkstyleAll
  - name: test
    image: c2.complang.tuwien.ac.at:5000/vadl-ci:f7222374638bccc355ba51bfcc2b17e9561204a4
    privileged: true
    commands:
      - ./gradlew test -i
    volumes:
      - name: docker
        path: /var/run/docker.sock
  - name: comment checkstyle report
    image: c2.complang.tuwien.ac.at:5000/drone-gitea-message:1411b3d7e54329473da2717d2ef09a06f13b3bc4
    settings:
      api_key:
        from_secret: ACCESS_TOKEN
      base_url: https://ea.complang.tuwien.ac.at
      message_file: build/reports/checkstyle/report.md
      delete_identifier: checkstyle-report-delete-id
    when:
      status: [ failure ]

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  ref:
    - refs/pull/**
    - refs/head/master

---

#
# Drone pipeline that tests the OpenVADL test suite with the old VADL backend.
# It executes the following steps on updates to a pull request or pushes to master:
#   - clone old vadl
#   - check if the ci-skip-old-vadl label is set by the PR
#   - checkout open-vadl in vadl/open-vadl
#   - assemble (old)vadl
#   - run at.ac.tuwien.complang.tests.OpenVADLTestSuite
#
# There might be a cyclic dependency between vadl and open-vadl (when making a breaking change in open-vadl).
# This would result in a failing PR.
# By setting the ci-skip-old-vadl label in the PR, you can skip the OpenVADLTestSuite execution.
#
kind: pipeline
type: docker
name: OpenVADL Test Suite

clone:
  disable: true

steps:
  - name: clone vadl
    image: c2.complang.tuwien.ac.at:5000/vadl-ci:f7222374638bccc355ba51bfcc2b17e9561204a4
    commands:
      - git clone git@ea.complang.tuwien.ac.at:vadl/vadl.git .

  # This step checks if the ci-skip-old-vadl label was set. It does this by sending a REST request to gitea.
  # The result is stored in the .env.pipeline file of the CI workspace directory.
  # This file must be sourced by the following steps to conditionally execute the step.
  - name: check for ci-skip-old-vadl label
    image: c2.complang.tuwien.ac.at:5000/vadl-ci:f7222374638bccc355ba51bfcc2b17e9561204a4
    environment:
      ACCESS_TOKEN:
        from_secret: ACCESS_TOKEN
    commands:
      - apk add --no-cache curl jq
      - ISSUE_NUMBER=$DRONE_PULL_REQUEST
      - |
        RESPONSE=$(curl -s -H "Authorization: token $ACCESS_TOKEN" -H 'accept: application/json' \
        "https://ea.complang.tuwien.ac.at/api/v1/repos/vadl/open-vadl/issues/$ISSUE_NUMBER/labels")
      - SKIP_TESTS=$(echo $RESPONSE | jq '.[] | select(.name == "ci-skip-old-vadl").name' | grep -c "ci-skip-old-vadl" || echo)
      - echo "SKIP_TESTS=$SKIP_TESTS" > .env.pipeline
      - echo "Skipping OpenVADLTestSuite... $SKIP_TESTS"

  - name: checkout open-vadl
    image: c2.complang.tuwien.ac.at:5000/vadl-ci:f7222374638bccc355ba51bfcc2b17e9561204a4
    commands:
      - git submodule update --init
      - git -C open-vadl fetch
      - git -C open-vadl checkout $DRONE_COMMIT

  - name: build vadl
    image: c2.complang.tuwien.ac.at:5000/vadl-ci:f7222374638bccc355ba51bfcc2b17e9561204a4
    commands:
      # Source to get the SKIP_TESTS variable set by the previous step
      - source .env.pipeline
      # If the SKIP_TESTS variable is set to 1, we will skip the command
      - '[ "$SKIP_TESTS" = "1" ] || make gradle-build'

  - name: run open-vadl test suite
    image: c2.complang.tuwien.ac.at:5000/vadl-ci:f7222374638bccc355ba51bfcc2b17e9561204a4
    commands:
      - source .env.pipeline
      - '[ "$SKIP_TESTS" = "1" ] || ./.gradlew test --tests at.ac.tuwien.complang.vadl.tests.OpenVADLTestSuite -i'
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      test.llvm.enabled: true

trigger:
  ref:
    - refs/pull/**

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
