kind: pipeline
type: docker
name: benchmarks

steps:
- name: install-vadl
  depends_on:
  - clone
  image: c2.complang.tuwien.ac.at:5000/embench-ci:85c310618236c1d7250908fbf7bc633f7f9d1867
  environment:
    ACCESS_TOKEN:
      from_secret: ACCESS_TOKEN
  commands:
  - ./install-vadl.sh

- name: build-vadl-sims
  depends_on:
  - install-vadl
  image: c2.complang.tuwien.ac.at:5000/embench-ci:85c310618236c1d7250908fbf7bc633f7f9d1867
  environment:
    ACCESS_TOKEN:
      from_secret: ACCESS_TOKEN
  commands:
  - ./build_vadl_sims_docker.sh

- name: run-benchmarks-aarch64
  depends_on:
  - build-vadl-sims
  image: c2.complang.tuwien.ac.at:5000/embench-ci:85c310618236c1d7250908fbf7bc633f7f9d1867
  commands:
  - ./benchmark-extras/run-benchmarks-aarch64.sh

- name: run-benchmarks-rv32
  depends_on:
  - run-benchmarks-aarch64
  image: c2.complang.tuwien.ac.at:5000/embench-ci:85c310618236c1d7250908fbf7bc633f7f9d1867
  commands:
  - ./benchmark-extras/run-benchmarks-rv32.sh

- name: run-benchmarks-rv32-lcb-clang
  depends_on:
  - run-benchmarks-rv32
  image: c2.complang.tuwien.ac.at:5000/embench-ci:85c310618236c1d7250908fbf7bc633f7f9d1867
  volumes:
  - name: disk
    path: /mnt
  commands:
  - export PATH=/drone/src/lcbw:$PATH
  - ./build_lcb_docker.sh
  - ./benchmark-extras/run-benchmarks-rv32-lcb-clang.sh

- name: run-benchmarks-spike-clang-lcb
  depends_on:
  - run-benchmarks-rv32-lcb-clang
  image: c2.complang.tuwien.ac.at:5000/embench-ci:85c310618236c1d7250908fbf7bc633f7f9d1867
  volumes:
  - name: disk
    path: /mnt
  commands:
  - export PATH=/drone/src/lcbw:$PATH
  - ./build_lcb_docker.sh
  - ./benchmark-extras/run-benchmarks-spike-clang-lcb.sh

- name: push-results
  depends_on:
  - run-benchmarks-rv32-lcb-clang
  image: c2.complang.tuwien.ac.at:5000/embench-ci:85c310618236c1d7250908fbf7bc633f7f9d1867
  environment:
    ACCESS_TOKEN:
      from_secret: ACCESS_TOKEN
  commands:
  - ./benchmark-extras/push-results.sh

trigger:
  ref:
  -  refs/heads/**

volumes:
- name: disk
  host:
    path: /var/disk

---
kind: pipeline
type: docker
name: merge

steps:
- name: ready-to-merge
  depends_on:
  - clone
  image: c2.complang.tuwien.ac.at:5000/embench-ci:85c310618236c1d7250908fbf7bc633f7f9d1867
  environment:
    ACCESS_TOKEN:
      from_secret: ACCESS_TOKEN
  commands:
  - echo ready to merge

trigger:
  ref:
  -  refs/pull/**
