name: Benchmark LCB

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'vadl/main/vadl/lcb/**'
      - 'vadl/test/vadl/lcb/**'
      - 'sys/**'

permissions:
  contents: read
  actions: write
  checks: write

jobs:
  riscv32:
    uses: ./.github/workflows/reusable-benchmark-publish.yml
    with:
      runner: self-hosted-x64
      benchmark-command: ./gradlew :vadl:test -i --tests "vadl.lcb.riscv.riscv32.EmbenchBenchmarkRiscv32Test" -Dtags.include=BenchmarkTest
      artifact-source: vadl/riscv32.csv
      artifact-name: ${{ github.event.repository.updated_at }}_${{ github.sha }}.csv
      destination-folder: data/lcb/riscv32/instruction-delta/results
      commit-message: 'data: Pushed LCB data'
      extra-env: |
        EMBENCH_BENCHMARK_RESULT_HOST_PATH=riscv32.csv
        EMBENCH_BENCHMARK_RESULT_GUEST_PATH=/src/embench/result/executed_instructions_relative.csv
    secrets: inherit
  riscv64:
    uses: ./.github/workflows/reusable-benchmark-publish.yml
    with:
      runner: self-hosted-x64
      benchmark-command: ./gradlew :vadl:test -i --tests "vadl.lcb.riscv.riscv64.EmbenchBenchmarkRiscv64Test" -Dtags.include=BenchmarkTest
      artifact-source: vadl/riscv64.csv
      artifact-name: ${{ github.event.repository.updated_at }}_${{ github.sha }}.csv
      destination-folder: data/lcb/riscv64/instruction-delta/results
      commit-message: 'data: Pushed LCB data'
      extra-env: |
        EMBENCH_BENCHMARK_RESULT_HOST_PATH=riscv64.csv
        EMBENCH_BENCHMARK_RESULT_GUEST_PATH=/src/embench/result/executed_instructions_relative.csv
    secrets: inherit
