name: Benchmark Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'sys/**'
      - 'vadl/main/vadl/ast/**'
      - 'vadl/main/vadl/error/**'
      - 'vadl/main/vadl/types/**'
      - 'vadl/main/vadl/utils/**'

permissions:
  contents: read
  actions: write
  checks: write

jobs:
  build:
    runs-on: self-hosted-x64
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: ./gradlew nativeBuild
      - name: Upload native binary
        uses: actions/upload-artifact@v4
        with:
           name: openvadl
           path: vadl-cli/build/native/nativeCompile/openvadl
           retention-days: 1

  aarch64:
    needs: build
    uses: ./.github/workflows/reusable-benchmark-publish.yml
    with:
      runner: self-hosted-x64
      download-artifact: openvadl
      benchmark-command: python3 scripts/benchmark/benchmark_frontend.py --openvadl-binary=./openvadl sys/aarch64/aarch64.vadl
      artifact-source: output/timings-mean.csv
      destination-folder: data/frontend/aarch64/native/results
      commit-message: 'data: Pushed frontend aarch64 native data'
    secrets: inherit
    
  aarch32:
    needs: build
    uses: ./.github/workflows/reusable-benchmark-publish.yml
    with:
      runner: self-hosted-x64
      download-artifact: openvadl
      benchmark-command: python3 scripts/benchmark/benchmark_frontend.py --openvadl-binary=./openvadl sys/aarch32/aarch32.vadl
      artifact-source: output/timings-mean.csv
      destination-folder: data/frontend/aarch32/native/results
      commit-message: 'data: Pushed frontend aarch32 native data'
    secrets: inherit

  rv32i:
    needs: build
    uses: ./.github/workflows/reusable-benchmark-publish.yml
    with:
      runner: self-hosted-x64
      download-artifact: openvadl
      benchmark-command: python3 scripts/benchmark/benchmark_frontend.py --openvadl-binary=./openvadl sys/risc-v/rv32i.vadl
      artifact-source: output/timings-mean.csv
      destination-folder: data/frontend/rv32i/native/results
      commit-message: 'data: Pushed frontend rv32i native data'
    secrets: inherit

  ppc64:
    needs: build
    uses: ./.github/workflows/reusable-benchmark-publish.yml
    with:
      runner: self-hosted-x64
      download-artifact: openvadl
      benchmark-command: python3 scripts/benchmark/benchmark_frontend.py --openvadl-binary=./openvadl sys/ppc64/ppc64.vadl
      artifact-source: output/timings-mean.csv
      destination-folder: data/frontend/ppc64/native/results
      commit-message: 'data: Pushed frontend ppc64 native data'
    secrets: inherit

  hexagon:
    needs: build
    uses: ./.github/workflows/reusable-benchmark-publish.yml
    with:
      runner: self-hosted-x64
      download-artifact: openvadl
      benchmark-command: python3 scripts/benchmark/benchmark_frontend.py --openvadl-binary=./openvadl sys/hexagon/hexagon.vadl
      artifact-source: output/timings-mean.csv
      destination-folder: data/frontend/hexagon/native/results
      commit-message: 'data: Pushed frontend hexagon native data'
    secrets: inherit