name: Benchmark RTL

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'vadl/main/vadl/rtl/**'
      - 'vadl/test/vadl/rtl/**'
      - 'sys/**'

permissions:
  contents: read
  actions: write
  checks: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: ./gradlew assemble testClasses -PFailOnWarnings
  riscv:
    needs: build
    uses: ./.github/workflows/reusable-benchmark-publish.yml
    with:
      runner: self-hosted-x64
      benchmark-command: ./gradlew test -i --tests "vadl.rtl.riscv.RtlRiscVBenchmarkTest" -Dtags.include=BenchmarkTest
      artifact-source: riscv_rtl_dec_benchmarks.csv
      artifact-name: ${{ github.event.repository.updated_at }}_${{ github.sha }}.csv
      destination-folder: data/rtl/riscv/benchmark
      commit-message: 'data: Pushed RTL data'
      extra-env: |
        RTL_DEC_BENCHMARK_RESULT_HOST_PATH=${{ github.workspace }}/riscv_rtl_dec_benchmarks.csv
    secrets: inherit
