name: Benchmark RTL

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'vadl/main/vadl/rtl/**'
      - 'vadl/test/vadl/rtl/**'
      - 'sys/**'

permissions:
  contents: read
  actions: write
  checks: write

jobs:
  riscv:
    uses: ./.github/workflows/reusable-benchmark-publish.yml
    with:
      runner: self-hosted-x64
      benchmark-command: ./gradlew :vadl:test -i --tests "vadl.rtl.riscv.RtlRiscVBenchmarkTest" -Dtags.include=BenchmarkTest
      artifact-source: vadl/riscv_rtl_dec_benchmarks.csv
      destination-folder: data/rtl/riscv/benchmark/results
      commit-message: 'data: Pushed RTL data'
      extra-env: |
        RTL_DEC_BENCHMARK_RESULT_HOST_PATH=riscv_rtl_dec_benchmarks.csv
    secrets: inherit
