name: Build LLVM17 base image

on:
  workflow_dispatch: # Allows manual triggering

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/openvadl/llvm17-base vadl/test/resources/images/llvm_riscv/llvm17_base_image

      - name: Push Docker image
        run: |
          docker push ghcr.io/openvadl/llvm17-base
