name: Build spike rv64im base image

on:
  workflow_dispatch: # Allows manual triggering

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: self-hosted-x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/openvadl/spike-rv64im-base-image vadl/test/resources/images/spike_rv64im/base_image

      - name: Push Docker image
        run: |
          docker push ghcr.io/openvadl/spike-rv64im-base-image
