name: Build RISC-V GNU Toolchain Image

on:
  workflow_dispatch: # Allows manual triggering

permissions:
  packages: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/reusable-image-build.yml
    strategy:
      matrix:
        target:
          - platform: linux/arm64
            runner: self-hosted-arm64
          - platform: linux/amd64
            runner: self-hosted-x64
    with:
      image: ghcr.io/openvadl/riscv-toolchain
      context: docker/iss/riscv-toolchain
      platform: ${{ matrix.target.platform }}
      runner: ${{ matrix.target.runner }}
      tags: |
        latest
        medany-rv32i-rv32im-rv32impriv-rv64i-rv64im-rv64impriv

  merge:
    needs: build
    uses: ./.github/workflows/reusable-image-merge.yml
    with:
      image: ghcr.io/openvadl/riscv-toolchain