name: Build spike rv32im base image

on:
  workflow_dispatch: # Allows manual triggering

permissions:
  packages: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/reusable-image-build.yml
    strategy:
      matrix:
        target:
          - platform: linux/arm64
            runner: self-hosted-arm64
          - platform: linux/amd64
            runner: self-hosted-x64
    secrets:
      X06_KEYCHAIN_PASSWORD: ${{ secrets.X06_KEYCHAIN_PASSWORD }}
    with:
      image: ghcr.io/openvadl/spike-rv32im-base-image
      context: vadl/test/resources/images/spike_rv32im/base_image
      platform: ${{ matrix.target.platform }}
      runner: ${{ matrix.target.runner }}

  merge:
    needs: build
    uses: ./.github/workflows/reusable-image-merge.yml
    secrets:
      X06_KEYCHAIN_PASSWORD: ${{ secrets.X06_KEYCHAIN_PASSWORD }}
    with:
      image: ghcr.io/openvadl/spike-rv32im-base-image