name: Build QEMU base image

on:
  workflow_dispatch: # Allows manual triggering

permissions:
  packages: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/reusable-image-build.yml
    strategy:
      matrix:
        target:
          - platform: linux/arm64
            runner: self-hosted-arm64
          - platform: linux/amd64
            runner: self-hosted-x64
    with:
      image: ghcr.io/openvadl/qemu-base
      context: docker/iss/qemu
      platform: ${{ matrix.target.platform }}
      runner: ${{ matrix.target.runner }}

  merge:
    needs: build
    uses: ./.github/workflows/reusable-image-merge.yml
    with:
      image: ghcr.io/openvadl/qemu-base