# Publishes the Doxygen reference manual on Github pages
name: OpenVADL Refman

on:
  push:
    branches:
      - "master"
    paths:
      - 'docs/**'


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted-x64
    container:
      image: ghcr.io/openvadl/doxygen:1.13.2
    name: Build refman and deploy
    steps:
      - name: Install Git and Tar
        run: apk add --no-cache git tar
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: cd docs && DOXYGEN=doxygen make open-vadl-html-refman
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/obj/doc/open-vadl-refman/html/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4