name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      test-task:
        description: 'The Gradle test task to run'
        required: true
        type: string
      runner:
        description: 'Runs-on property'
        default: 'self-hosted'
        type: string
        required: false

jobs:
  test:
    name: ${{ inputs.test-task }}
    runs-on: ${{ inputs.runner }}
    env:
      isCI: true
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: ./gradlew ${{ inputs.test-task }}
        env:
          isCI: true
      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
          detailed_summary: true
          include_passed: true
      - name: Upload Raw Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-report-xml
          path: '**/build/test-results/**/TEST-*.xml'
          retention-days: 3
      - if: failure()
        uses: andymckay/cancel-action@0.5
